export const posOptions = [
  { label: "All Positions", value: "All Positions" },
  { label: "Point Guards", value: "PG" },
  { label: "Shooting Guards", value: "SG" },
  { label: "Small Forwards", value: "SF" },
  { label: "Power Forwards", value: "PF" },
  { label: "Centers", value: "C" },
];

export const teamOptions = [
  { label: "All Teams", value: "All Teams" },
  { label: "Los Angeles Lakers", value: "LAL" },
  { label: "Boston Celtics", value: "BOS" },
  { label: "Golden State Warriors", value: "GSW" },
  { label: "Cleveland Cavaliers", value: "CLE" },
  { label: "San Antonio Spurs", value: "SAS" },
  { label: "Philadelphia 76ers", value: "PHI" },
  { label: "Miami Heat", value: "MIA" },
  { label: "Chicago Bulls", value: "CHI" },
  { label: "Detroit Pistons", value: "DET" },
  { label: "Phoenix Suns", value: "PHX" },
  { label: "Houston Rockets", value: "HOU" },
  { label: "New York Knicks", value: "NYK" },
  { label: "Dallas Mavericks", value: "DAL" },
  { label: "Oklahoma City Thunder", value: "OKC" },
  { label: "Utah Jazz", value: "UTA" },
  { label: "Los Angeles Clippers", value: "LAC" },
  { label: "Milwaukee Bucks", value: "MIL" },
  { label: "Atlanta Hawks", value: "ATL" },
  { label: "Denver Nuggets", value: "DEN" },
  { label: "Toronto Raptors", value: "TOR" },
  { label: "Portland Trailblazers", value: "POR" },
  { label: "Indiana Pacers", value: "IND" },
  { label: "New Orleans Pelicans", value: "NOP" },
  { label: "Washington Wizards", value: "WAS" },
  { label: "Memphis Grizzlies", value: "MEM" },
  { label: "Orlando Magic", value: "ORL" },
  { label: "Sacramento Kings", value: "SAC" },
  { label: "Minnesotta Timberwolves", value: "MIN" },
  { label: "Charlotte Hornets", value: "CHA" },
  { label: "Brooklyn Nets", value: "BRK" },
];

export const badgeOptions = [
  { label: "All Badges", value: 0 },
  { label: "Deadeye Shooter", value: 1 },
  { label: "Tough Shot Maker", value: 2 },
  { label: "Lob/Putback/Dunk Master", value: 3 },
  { label: "Limitless Range", value: 4 },
  { label: "Middy Magician", value: 5 },
  { label: "Foul Drawer", value: 6 },
  { label: "Acrobatic Finisher", value: 7 },
  { label: "Contact Finisher", value: 8 },
  { label: "Post Move Technician", value: 9 },

  { label: "Offensive Engine", value: 10 },
  { label: "Dime Dropper", value: 11 },
  { label: "Off-Ball Gravity", value: 12 },
  { label: "Houdini Handles", value: 13 },

  { label: "Lockdown Post Defender", value: 14 },
  { label: "Perimeter Handcuffs", value: 15 },
  { label: "Shot Block Artist", value: 16 },
  { label: "Switchable Specialist", value: 17 },
  { label: "Defensive Anchor", value: 18 },
  { label: "Pick Pocket/Interceptor", value: 19 },
  { label: "High IQ Defender", value: 20 },
  { label: "High Energy Defender", value: 21 },

  { label: "Rebound Magnet", value: 22 },
];
