export const posOptions = [
  { label: "All Positions", value: "All Positions" },
  { label: "Point Guards", value: "PG" },
  { label: "Shooting Guards", value: "SG" },
  { label: "Small Forwards", value: "SF" },
  { label: "Power Forwards", value: "PF" },
  { label: "Centers", value: "C" },
];

export const teamOptions = [
  { label: "All Teams", value: "All Teams" },
  { label: "Los Angeles Lakers", value: "LAL" },
  { label: "Boston Celtics", value: "BOS" },
  { label: "Golden State Warriors", value: "GSW" },
  { label: "Cleveland Cavaliers", value: "CLE" },
  { label: "San Antonio Spurs", value: "SAS" },
  { label: "Philadelphia 76ers", value: "PHI" },
  { label: "Miami Heat", value: "MIA" },
  { label: "Chicago Bulls", value: "CHI" },
  { label: "Detroit Pistons", value: "DET" },
  { label: "Phoenix Suns", value: "PHX" },
  { label: "Houston Rockets", value: "HOU" },
  { label: "New York Knicks", value: "NYK" },
  { label: "Dallas Mavericks", value: "DAL" },
  { label: "Oklahoma City Thunder", value: "OKC" },
  { label: "Utah Jazz", value: "UTA" },
  { label: "Los Angeles Clippers", value: "LAC" },
  { label: "Milwaukee Bucks", value: "MIL" },
  { label: "Atlanta Hawks", value: "ATL" },
  { label: "Denver Nuggets", value: "DEN" },
  { label: "Toronto Raptors", value: "TOR" },
  { label: "Portland Trailblazers", value: "POR" },
  { label: "Indiana Pacers", value: "IND" },
  { label: "New Orleans Pelicans", value: "NOP" },
  { label: "Washington Wizards", value: "WAS" },
  { label: "Memphis Grizzlies", value: "MEM" },
  { label: "Orlando Magic", value: "ORL" },
  { label: "Sacramento Kings", value: "SAC" },
  { label: "Minnesotta Timberwolves", value: "MIN" },
  { label: "Charlotte Hornets", value: "CHA" },
  { label: "Brooklyn Nets", value: "BRK" },
];

export const badgeOptions = [
  { label: "All Badges", value: "All Badges" },
  { label: "Deadeye Shooter", value: "Deadeye Shooter" },
  { label: "Tough Shot Maker", value: "Tough Shot Maker" },
  { label: "Lob/Putback/Dunk Master", value: "Lob/Putback/Dunk Master" },
  { label: "Limitless Range", value: "Limitless Range" },
  { label: "Middy Magician", value: "Middy Magician" },
  { label: "Foul Drawer", value: "Foul Drawer" },
  { label: "Acrobatic Finisher", value: "Acrobatic Finisher" },
  { label: "Contact Finisher", value: "Contact Finisher" },
  { label: "Post Move Technician", value: "Post Move Technician" },

  { label: "Offensive Engine", value: "Offensive Engine" },
  { label: "Dime Dropper", value: "Dime Dropper" },
  { label: "Offensive Gravity", value: "Offensive Gravity" },
  { label: "Houdini Handles", value: "Houdini Handles" },

  { label: "Lockdown Post Defender", value: "Lockdown Post Defender" },
  { label: "Perimeter Handcuffs", value: "Perimeter Handcuffs" },
  { label: "Shot Block Artist", value: "Shot Block Artist" },
  { label: "Switchable Specialist", value: "Switchable Specialist" },
  { label: "Defensive Anchor", value: "Defensive Anchor" },
  { label: "Pick Pocket/Interceptor", value: "Pick Pocket/Interceptor" },
  { label: "High IQ Defender", value: "High IQ Defender" },
  { label: "High Energy Defender", value: "High Energy Defender" },

  { label: "Rebound Magnet", value: "Rebound Magnet" },
];